# Generated by Django 4.2.28 on 2026-03-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analysisjob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='estimated_pay',
        ),
    ]
