# Generated by Django 4.2.28 on 2026-03-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_analysisresult_estimated_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='estimated_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
