# Generated by Django 4.2.28 on 2026-03-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analysisresult_estimated_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='estimated_pay',
        ),
    ]
